language: csharp
solution: FoodStorage.sln

#dist: trusty
mono: none
dotnet: 3.0.100
#dotnet: 2.1.500

addons:
  sonarcloud:
    organization: "zanuccod"
    token:
      secure: "cf00312ac3711956b9ba30c16a65cfb521ea837e"

script:
 - dotnet restore
 - dotnet test -c Release ./FoodStorage/FoodStorageTest
 - dotnet test -c Release ./WebApi/WebApiTest
 - sonar-scanner