language: csharp
solution: FoodStorage.sln

mono: none
dotnet: 3.0.100

os:
  - linux
  - osx
  - windows 

script:
 - dotnet restore
 - dotnet test -c Release ./FoodStorage/FoodStorageTest
 - dotnet test -c Release ./WebApi/WebApiTest