language: csharp
solution: FoodStorage.sln
dist: trusty

mono: none
dotnet: 3.0.100

addons:
  sonarcloud:
    organization: "zanuccod"
    token:
      secure: "4b75f20b2d7d6f837f85864beaa94a0f1638562e" # encrypted value of your token

script:
 - dotnet restore
 - dotnet test -c Release ./FoodStorage/FoodStorageTest
 - dotnet test -c Release ./WebApi/WebApiTest
 - sonar-scanner
