language: csharp
solution: FoodStorage.sln

mono: none
dotnet: 3.0.100

 install:
  - nuget restore FoodStorage.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release FoodStorage.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./FoodStorage.FoodStorageTests/bin/Release/FoodStorageTests.dll